### ISSUE TITLE
Can we make licenses dct:licenses?

### ISSUE THREAD

**Issue by tthoeye** [Fedict/dcattools#1]
Is it possible to make 
https://github.com/Fedict/dcattools/blob/c4ad6eb62f8d27bffeca9b39aa5487da86b3c207/dist/cfg/vlaanderen/data-license.ttl#L8 a http://purl.org/dc/terms/license?

What are the consequences? Just asking ;)

**Comment by tthoeye** [comment]
Als can you change the exactMatch to http://id.vlaanderen.be/licentie/gratis-open-data-licentie-1.2?

**Comment by barthanssens** [comment]
Well, changing L8 (data.gov.be URI) will break the license is displayed on the data.gov.be site, because it maps free text found in datasets properties (which should be an URI in the first place) to the Drupal ID...

In general: mapping files are used to correct / map stuff to both the manually created drupal taxonomy IDs (the subject URI) _and_ the properties in the DCAT-AP export (which is available as one big RDF/XML or N-Triples file), so in this case the exactMatch is used to add the correct license property (dcterms:license), see also the sparql-map-license.txt for the SPARQL update query that does exactly that.

Now, it would be nicer if Drupal would be able to import the DCAT-AP "as-is", without additional Drupal-ish ID's, but due to practical constraints this wasn't feasible/more work than this set of scripts :-/
