### ISSUE TITLE
How do you store DCAT-AP data

### ISSUE THREAD

**Issue by epos-eu** [Fedict/dcattools#2]
I know it's not perhaps even an issue, and it might be not the most appropriate place to make this question.

However we are interested in understanding how do you eventually store the DCAT-AP files.
Are they stored in Drupal? What is the database you are using?

Can you provide additional infos or pointers to existing documentation?

thanks

**Comment by barthanssens** [comment]
Well, the conversions are run locally using embedded RDF4J Nativestore, and eventually the full DCAT-AP file gets pushed to github, so it can be harvested by the EU Data Portal (IIRC they have a combination of CKAN/Virtuoso and Drupal, but I'm not sure)

Data.gov.be is a plain Drupal 7 website, which does not know anything about DCAT-AP, and doesn't store the RDF at all.
A small conversion tool is used to transform DCAT-AP into something Drupal understands (JSON), and to send the updates to Drupal (via the RestWS module).

That part is pretty much custom made, since the DCAT-AP had to be mapped to the exact field names used in our Drupal content types (and some manual changes are needed when a new organisation is added)

It is somewhat time-consuming when something needs to be changed, but has the benefit that (if needed in the future), we can switch to another platform that does understand DCAT-AP, and I don't have to worry about the maintenance of the platform itself (we host dozens of other Drupal sites, so there is a dedicated team for handling Drupal security updates, backup, maintenance etc.... which we don't have for e.g. CKAN)

Feel free to mail me at bart.hanssens[at]bosa.fgov.be if you need more info.
